### ISSUE TITLE
translation missing:en.financial_monitoring

### ISSUE THREAD

**Issue by jackytran84** [soualid/redmine-financial-monitoring#3]
Page not found

The page you were trying to access doesn't exist or has been removed.
![image](https://user-images.githubusercontent.com/28912965/26866327-dc57d4c4-4b8a-11e7-8b34-06d4f1987547.png)

**Comment by soualid** [comment]
Hello,

What is the URL of the page the link is pointing to ?

**Comment by jackytran84** [comment]
Hello

[image: Inline image 2]
[image: Inline image 1]

**Comment by soualid** [comment]
Images are not visible in your last message, sorry.
